c_compiler_version:      # [liunx]
  - 5.4                  # [linux]
cxx_compiler_version:    # [linux]
  - 5.4                  # [linux]
c_compiler:              # [win]
  - vs2015               # [win]
cxx_compiler:            # [win]
  - vs2015               # [win]
cudatoolkit:
  - 9.0
r_implementation:
  - r-base
  - mro-base  # [not osx and not linux32 and not win32]
